// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package biu_test_pkg;
    typedef struct packed {
        logic [7:0] next;
    } biu_test__cfg0__datIn0__in_t;

    typedef struct packed {
        logic [7:0] next;
    } biu_test__cfg0__datIn1__in_t;

    typedef struct packed {
        biu_test__cfg0__datIn0__in_t  datIn0;
        biu_test__cfg0__datIn1__in_t  datIn1;
    } biu_test__cfg0__in_t;

    typedef struct packed {
        logic hwclr;
    } biu_test__ctrl1__op_en__in_t;

    typedef struct packed {
        biu_test__ctrl1__op_en__in_t  op_en;
    } biu_test__ctrl1__in_t;

    typedef struct packed {
        logic [7:0] next;
        logic we;
    } biu_test__status0__datOut__in_t;

    typedef struct packed {
        biu_test__status0__datOut__in_t  datOut;
    } biu_test__status0__in_t;

    typedef struct packed {
        logic next;
    } biu_test__reg2__INT_cpu_enable_3a353fbe_resetsignal_bd56b7e2__in_t;

    typedef struct packed {
        logic next;
    } biu_test__reg2__INT_cpu_enable__in_t;

    typedef struct packed {
        biu_test__reg2__INT_cpu_enable_3a353fbe_resetsignal_bd56b7e2__in_t  INT_cpu;
        biu_test__reg2__INT_cpu_enable__in_t  INT_cpu_enable;
    } biu_test__reg2__in_t;

    typedef struct packed {
        logic [31:0] dat;
    } biu_test__fifo_mem__in_t;

    typedef struct packed {
        logic rstn;
        biu_test__cfg0__in_t  cfg0;
        biu_test__ctrl1__in_t  ctrl1;
        biu_test__status0__in_t  status0;
        biu_test__reg2__in_t  reg2;
        biu_test__fifo_mem__in_t [1:0] fifo_mem;
    } biu_test__in_t;

    typedef struct packed {
        logic [7:0] value;
    } biu_test__cfg0__datIn0__out_t;

    typedef struct packed {
        logic [7:0] value;
    } biu_test__cfg0__datIn1__out_t;

    typedef struct packed {
        biu_test__cfg0__datIn0__out_t  datIn0;
        biu_test__cfg0__datIn1__out_t  datIn1;
    } biu_test__cfg0__out_t;

    typedef struct packed {
        logic value;
    } biu_test__ctrl1__op_en__out_t;

    typedef struct packed {
        biu_test__ctrl1__op_en__out_t  op_en;
    } biu_test__ctrl1__out_t;

    typedef struct packed {
        logic [7:0] value;
    } biu_test__status0__datOut__out_t;

    typedef struct packed {
        biu_test__status0__datOut__out_t  datOut;
    } biu_test__status0__out_t;

    typedef struct packed {
        logic value;
    } biu_test__reg2__INT_cpu_enable_3a353fbe_resetsignal_bd56b7e2__out_t;

    typedef struct packed {
        logic value;
    } biu_test__reg2__INT_cpu_enable__out_t;

    typedef struct packed {
        biu_test__reg2__INT_cpu_enable_3a353fbe_resetsignal_bd56b7e2__out_t  INT_cpu;
        biu_test__reg2__INT_cpu_enable__out_t  INT_cpu_enable;
        logic intr;
    } biu_test__reg2__out_t;

    typedef struct packed {
        logic write_en;
        logic [5:0] addr;
        logic [31:0] dat;
    } biu_test__fifo_mem__out_t;

    typedef struct packed {
        biu_test__cfg0__out_t  cfg0;
        biu_test__ctrl1__out_t  ctrl1;
        biu_test__status0__out_t  status0;
        biu_test__reg2__out_t  reg2;
        biu_test__fifo_mem__out_t [1:0] fifo_mem;
    } biu_test__out_t;
endpackage